<#
.SYNOPSIS
    Compresses forensic artifacts into a ZIP archive for retrieval.

.DESCRIPTION
    Validates the existence of forensic output files generated by the processing step.
    If all files are present, compresses them into a single ZIP archive.

    Designed to be run in a polling loop; missing files trigger an exception,
    causing the SOAR workflow to retry until files appear or timeout occurs.

.PARAMETER json_input
    A JSON string containing configuration parameters.
    Required: forensic_results, forensic_analysis_path, system_hostname,
              analysis_timestamp, cleaned_browser_name

.OUTPUTS
    JSON string containing zip_file_path on success.
#>

param (
    [Parameter(Mandatory=$true)]
    [string]$json_input
)

$ErrorActionPreference = 'Stop'

# Parse Input
$json_data = $json_input | ConvertFrom-Json
$forensic_results       = $json_data.forensic_results
$forensic_analysis_path = $json_data.forensic_analysis_path
$system_hostname        = $json_data.system_hostname
$analysis_timestamp     = $json_data.analysis_timestamp
$cleaned_browser_name   = $json_data.cleaned_browser_name

# Initialize State
$exception_messages = @()
$zip_file_path = $null

# -------------------------------------------------------------------------
# Phase 1: Validation (Retry Trigger)
# -------------------------------------------------------------------------
foreach ($file in $forensic_results) {
    if (-not (Test-Path -Path $file)) {
        $exception_messages += "Missing forensic result file: $file"
    }
}

# -------------------------------------------------------------------------
# Phase 2: Compression
# -------------------------------------------------------------------------
if ($exception_messages.Count -eq 0) {
    try {
        $zip_file_name = "${system_hostname}-${cleaned_browser_name}-${analysis_timestamp}.zip"
        $zip_file_path = Join-Path -Path $forensic_analysis_path -ChildPath $zip_file_name

        Compress-Archive -Path $forensic_results -DestinationPath $zip_file_path -Force
    } catch {
        $exception_messages += $_.Exception.Message
    }
}

# -------------------------------------------------------------------------
# Output Construction
# -------------------------------------------------------------------------
$has_processing_errors = $exception_messages.Count -gt 0

$json_output = [PSCustomObject]@{
    "has_processing_errors" = $has_processing_errors
    "zip_file_path"         = $zip_file_path
}

if ($has_processing_errors) {
    $json_output | Add-Member -NotePropertyName "exception_messages" -NotePropertyValue $exception_messages
}

$json_output | ConvertTo-Json -Depth 2
