<#
.SYNOPSIS
    Compresses forensic artifacts into a ZIP archive for retrieval.

.DESCRIPTION
    Validates the existence of forensic output files generated by the processing step.
    If all files are present, it compresses them into a single ZIP archive.
    This script is designed to be run in a loop; if files are missing, it throws an exception,
    triggering a retry in the parent SOAR workflow until files appear or timeout occurs.

.PARAMETER json_input
    A JSON string containing configuration parameters.
    Required fields:
    - forensic_results (array of file paths)
    - forensic_analysis_path (string)
    - system_hostname (string)
    - analysis_timestamp (string)
    - selected_browser (string)

.OUTPUTS
    JSON string containing:
    - has_processing_errors (boolean)
    - zip_file_path (string)
    - exception_messages (array)

.EXAMPLE
    .\hindsight_collection.ps1 -json_input '{"forensic_results": ["C:\\path\\to\\result.xlsx"], ...}'
#>

param (
    [Parameter(Mandatory=$true, HelpMessage="JSON input string provided by the SOAR workflow.")]
    [string]$json_input
)

# Enforce strict variable checking
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# -------------------------------------------------------------------------
# Parse Input
# -------------------------------------------------------------------------
$json_data = $json_input | ConvertFrom-Json
$forensic_results_files = $json_data.forensic_results  # Array of expected file paths
$forensic_analysis_path = $json_data.forensic_analysis_path
$system_hostname        = $json_data.system_hostname
$analysis_timestamp     = $json_data.analysis_timestamp
$selected_browser       = $json_data.selected_browser

# -------------------------------------------------------------------------
# Initialize State Variables
# -------------------------------------------------------------------------
$has_processing_errors = $false
$exception_messages    = @()
$zip_file_path         = $null

# -------------------------------------------------------------------------
# Phase 1: Validation (Retry Trigger)
# -------------------------------------------------------------------------
# Check if all expected files exist. If not, throw detailed error to trigger workflow retry.
foreach ($file in $forensic_results_files) {
    try {
        if (-not (Test-Path -Path $file)) {
            throw "Missing forensic result file: $file"
        }
    } catch {
        $exception_messages += $_.Exception.Message
    }
}

$has_processing_errors = [bool]($exception_messages.Count)

# -------------------------------------------------------------------------
# Phase 2: Compression
# -------------------------------------------------------------------------
if (-not $has_processing_errors) {
    try {
        # Construct ZIP file name
        $cleaned_browser_name = $selected_browser -replace "\s", "-"
        $zip_file_name = "${system_hostname}-${cleaned_browser_name}-${analysis_timestamp}.zip"
        $zip_file_path = Join-Path -Path $forensic_analysis_path -ChildPath $zip_file_name

        # Compress forensic results into a ZIP archive
        Compress-Archive -Path $forensic_results_files -DestinationPath $zip_file_path -Force
    } catch {
        $exception_messages += $_.Exception.Message
    }
}

# -------------------------------------------------------------------------
# Phase 3: Verification
# -------------------------------------------------------------------------
$has_processing_errors = [bool]($exception_messages.Count)

if (-not $has_processing_errors) {
    try {
        if (-not (Test-Path -Path $zip_file_path)) {
            throw "ZIP file is missing after compression operation."
        }
    } catch {
        $exception_messages += $_.Exception.Message
    }
}

# -------------------------------------------------------------------------
# Output Construction
# -------------------------------------------------------------------------
$has_processing_errors = [bool]($exception_messages.Count)

if ($has_processing_errors) {
    $json_output = [PSCustomObject]@{
        "has_processing_errors" = $has_processing_errors
        "exception_messages"    = $exception_messages
    }
} else {
    $json_output = [PSCustomObject]@{
        "has_processing_errors" = $has_processing_errors
        "zip_file_path"         = $zip_file_path
    }
}

$json_output | ConvertTo-Json -Depth 2 | Out-String
