<#
.SYNOPSIS
    Compresses forensic artifacts into a ZIP archive for retrieval.

.DESCRIPTION
    This script validates the existence of artifacts generated by the Hindsight
    processing step and compresses them into a single ZIP archive for retrieval.

    The script operates in two phases:

    1. Artifact Validation - Verifies that all expected output files from the
       processing step exist. If any files are missing, the script returns an
       error to trigger the SOAR retry loop.

    2. Archive Compression - Creates a ZIP archive containing all validated
       artifacts, named with the hostname, browser, and timestamp for easy
       identification.

    The script guarantees JSON output for SOAR workflow integration, capturing
    any errors that occur without interrupting the automation pipeline.

.PARAMETER json_input
    JSON string containing the configuration object.
    Required fields:
        - expected_artifact_paths: Array of file paths to validate and compress.
        - working_directory_path: Directory where the ZIP archive will be created.
        - target_hostname: Endpoint hostname for archive naming.
        - target_browser: Browser name for archive naming.
        - execution_timestamp: Timestamp from processing phase for archive naming.

.OUTPUTS
    JSON object with the following properties:
        - has_processing_errors: Boolean indicating if any errors occurred.
        - compressed_archive_path: Full path to the created ZIP archive.
        - target_browser: The browser name (for downstream notifications).
        - target_hostname: The endpoint hostname (for downstream notifications).
        - execution_timestamp: The collection timestamp (for downstream notifications).
        - exception_messages: Array of error messages (only present if errors occurred).

.EXAMPLE
    $params = @{
        expected_artifact_paths = @("C:\Temp\Hindsight\output1.xlsx", "C:\Temp\Hindsight\output2.xlsx")
        working_directory_path = "C:\Temp\Hindsight"
        target_hostname = "WORKSTATION01"
        target_browser = "Google Chrome"
        execution_timestamp = "2024-01-15T14-30"
    } | ConvertTo-Json
    .\hindsight_collection.ps1 -json_input $params
#>

param (
    [Parameter(Mandatory=$true)]
    [string]$json_input
)

$ErrorActionPreference = 'Stop'

# Clear all variables to prevent stale values from previous session runs
$parsed_config           = $null
$expected_artifact_paths = $null
$working_directory_path  = $null
$target_hostname         = $null
$target_browser          = $null
$execution_timestamp     = $null
$compressed_archive_path = $null
$sanitized_browser_name  = $null
$archive_filename        = $null
$exception_messages      = @()

# Parse the JSON input and extract configuration parameters
$parsed_config           = $json_input | ConvertFrom-Json
$expected_artifact_paths = $parsed_config.expected_artifact_paths
$working_directory_path  = $parsed_config.working_directory_path
$target_hostname         = $parsed_config.target_hostname
$target_browser          = $parsed_config.target_browser
$execution_timestamp     = $parsed_config.execution_timestamp

# -----------------------------------------------------------------------------
# Phase 1: Artifact Validation
# Verifies all expected files exist; missing files trigger SOAR retry loop
# -----------------------------------------------------------------------------
foreach ($artifact_file_path in $expected_artifact_paths) {
    if (-not (Test-Path -Path $artifact_file_path)) {
        $exception_messages += "Artifact not ready: $artifact_file_path"
    }
}

# -----------------------------------------------------------------------------
# Phase 2: Archive Compression
# Creates ZIP archive containing all validated artifacts
# -----------------------------------------------------------------------------
if ($exception_messages.Count -eq 0) {
    try {
        # Normalize browser name for safe file system usage
        $sanitized_browser_name = $target_browser -replace "\s", "-"
        $archive_filename = "${target_hostname}-${sanitized_browser_name}-${execution_timestamp}.zip"
        $compressed_archive_path = Join-Path -Path $working_directory_path -ChildPath $archive_filename

        Compress-Archive -Path $expected_artifact_paths -DestinationPath $compressed_archive_path -Force
    } catch {
        $exception_messages += $_.Exception.Message
    }
}

# -----------------------------------------------------------------------------
# Build Result Object
# Assembles output for SOAR workflow consumption with all relevant metadata
# -----------------------------------------------------------------------------
$script_result = [PSCustomObject]@{
    has_processing_errors   = $exception_messages.Count -gt 0
    compressed_archive_path = $compressed_archive_path
    target_browser          = $target_browser
    target_hostname         = $target_hostname
    execution_timestamp     = $execution_timestamp
}

# Append exception details only when errors occurred
if ($exception_messages.Count -gt 0) {
    $script_result | Add-Member -NotePropertyName "exception_messages" -NotePropertyValue $exception_messages
}

$script_result | ConvertTo-Json -Depth 2
